# -*- coding: utf-8 -*-
"""PalmerPenguinsM4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Eul0NaSnStbGJZXs9X0yquWFdiw05iGW
"""

# Palmer Penguins
# Raynette Brown
# 09.25.20526
# Uses branches to explore Palmer Penguin statistics

import math #Import the math module

# constants representing the species and count
SP_CHINSTRAP = "Chinstrap"
SP_GENTOO = "Gentoo"
SP_ADELIE = "Adelie"

TOTAL_SPECIES = 3

# add constants for the number of penguins
NUM_CHINSTRAP = 68
NUM_GENTOO = 123
NUM_ADELIE = 151

#calculate the total number of penguins
total_penguins = NUM_CHINSTRAP + NUM_GENTOO + NUM_ADELIE

#calculate the average number of penguins per species
average_penguins = total_penguins/TOTAL_SPECIES

#calculate the percentage of each species
chinstrap_percent = NUM_CHINSTRAP / total_penguins * 100
gentoo_percent = NUM_GENTOO / total_penguins * 100
adelie_percent = NUM_ADELIE / total_penguins * 100

#mathModule
average_penguins_rouneded_up = math.ceil(average_penguins)

# List of species Names
species_names = [
    SP_CHINSTRAP,
    SP_GENTOO,
    SP_ADELIE
]

#Species Counts
species_counts = [
    NUM_CHINSTRAP,
    NUM_GENTOO,
    NUM_ADELIE
]

#Determine number of species using len()
total_species = len(species_names)

#Calculate the total number of penguins using sum()
total_penguins = sum(species_counts)

#Calculate the average number of penguins per species
average_penguins = total_penguins / total_species

#math.ceil()
average_penguins_rouneded_up = math.ceil(average_penguins)

#Calculate the species percentages using list indexes
chinstrap_percent = species_counts[0] / total_penguins * 100
gentoo_percent = species_counts[1] / total_penguins * 100
adelie_percent = species_counts[2] / total_penguins * 100

#Find the species with the most and fewest observations
largest_count = max(species_counts)
smallest_count = min(species_counts)

#Use the index() list method to determine where those values occur
largest_index = species_counts.index(largest_count)
smallest_index = species_counts.index(smallest_count)

#Use index() to retrieve the corresponding species names:
largest_species = species_names[largest_index]
smallest_species = species_names[smallest_index]

# List of species counts
species_counts = [NUM_CHINSTRAP, NUM_GENTOO, NUM_ADELIE]

# List of species percentages
species_percentages = [
    chinstrap_percent,
    gentoo_percent,
    adelie_percent
]


# output the species names with introductory text

print("Introducing the Palmer Penguins")
print("\t" + SP_CHINSTRAP + "!")
print("\t" + SP_GENTOO + "!")
print("and last but not least...")
print("\t" + SP_ADELIE + "!")
print()


print(f"There are a total of {total_penguins} penguins in the dataset.")
print(f"The average number of penguins per species is "
      f"{average_penguins:.1f}.")
print(f"The avergage number of penguins rounded up is {average_penguins_rouneded_up}.")
print()
print(f"{SP_CHINSTRAP}: {NUM_CHINSTRAP} ({chinstrap_percent:.2f}%)")
print(f"{SP_GENTOO}: {NUM_GENTOO} ({gentoo_percent:.2f}%)")
print(f"{SP_ADELIE}: {NUM_ADELIE} ({adelie_percent:.2f}%)")
print()
print(f"The species with the most observations is {largest_species} with {largest_count} penguins.")
print(f"The species with the fewest observations is {smallest_species} with {smallest_count} penguins.")

# promp the user to select a species
print()
print("Explore a species")
species_choice = input ("Enter Chinstrap, Gentoo, or Adelie: ")

# validate species selection
if species_choice not in species_names:
  print(species_choice + " is not one of the species in this dataset.")
else:
  # Determine the selected species
  if species_choice == species_names[0]:
    selected_index = 0
  elif species_choice == species_names[1]:
    selected_index = 1
  else:
    selected_index = 2

  # classify the selected species
  selected_species = species_names[selected_index]
  selected_count = species_counts[selected_index]
  selected_percent = species_percentages[selected_index]

  # Classify the selected speices by percent
  if selected_percent < 25:
    size_category = "small"
  elif (selected_percent >= 25) and (selected_percent < 40):
    size_category = "medium"
  else: size_category = "large"

  # Species Poistion
  if (selected_species == largest_species) or \
        (selected_species == smallest_species):
      if selected_species == largest_species:
        position_description = "largest"
      else:
        position_description = "smallest"
  else:
    position_description = "middle-sized"

  # Selected speices count by average
  average_position = "above" if selected_count > average_penguins else "below"

  # Display the selected species Stats
  print()
  print(f"{selected_species} has {selected_count} observations, "
        f"representing {selected_percent:.2f}% of the dataset.")
  print(f"{selected_species} is classified as a {size_category} species group.")
  print(f"{selected_species} is the {position_description} species group.")
  print(f"Its observation count is {average_position} the dataset average."
        f"of {average_penguins:.1f} ")